# -*- coding: utf-8 -*-
"""Quizzer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16feX7zs5-BqtlwU-Ir95vKutOEJgCcO3
"""

import streamlit as st
import random

# -----------------------
# POLYATOMIC IONS DATABASE
# -----------------------
# Now each ion has "formula" and "charge" separately
polyatomic_ions = {
    "1- Charge": {
        "Acetate": {"formula": "C2H3O2", "charge": "-"},
        "Bicarbonate": {"formula": "HCO3", "charge": "-"},
        "Bromate": {"formula": "BrO3", "charge": "-"},
        "Perchlorate": {"formula": "ClO4", "charge": "-"},
        "Chlorate": {"formula": "ClO3", "charge": "-"},
        "Chlorite": {"formula": "ClO2", "charge": "-"},
        "Hypochlorite": {"formula": "ClO", "charge": "-"},
        "Hydroxide": {"formula": "OH", "charge": "-"},
        "Iodate": {"formula": "IO3", "charge": "-"},
        "Nitrate": {"formula": "NO3", "charge": "-"},
        "Nitrite": {"formula": "NO2", "charge": "-"},
        "Permanganate": {"formula": "MnO4", "charge": "-"},
        "Cyanide": {"formula": "CN", "charge": "-"},
        "Thiocyanate": {"formula": "SCN", "charge": "-"}
    },
    "2- Charge": {
        "Carbonate": {"formula": "CO3", "charge": "2-"},
        "Chromate": {"formula": "CrO4", "charge": "2-"},
        "Dichromate": {"formula": "Cr2O7", "charge": "2-"},
        "Oxalate": {"formula": "C2O4", "charge": "2-"},
        "Silicate": {"formula": "SiO3", "charge": "2-"},
        "Sulfate": {"formula": "SO4", "charge": "2-"},
        "Sulfite": {"formula": "SO3", "charge": "2-"},
        "Tartrate": {"formula": "C4H4O6", "charge": "2-"},
        "Thiosulfate": {"formula": "S2O3", "charge": "2-"},
        "Hydrogen Phosphate": {"formula": "HPO4", "charge": "2-"}
    },
    "3- Charge": {
        "Phosphate": {"formula": "PO4", "charge": "3-"},
        "Phosphite": {"formula": "PO3", "charge": "3-"},
        "Arsenate": {"formula": "AsO4", "charge": "3-"}
    },
    "Miscellaneous": {
        "Cadmium Ion": {"formula": "Cd", "charge": "2+"},
        "Silver Ion": {"formula": "Ag", "charge": "+"},
        "Zinc Ion": {"formula": "Zn", "charge": "2+"},
        "Ammonium": {"formula": "NH4", "charge": "+"},
        "Mercury (I)": {"formula": "Hg2", "charge": "2+"},
        "Mercury (II)": {"formula": "Hg", "charge": "2+"},
        "Peroxide": {"formula": "O2", "charge": "2-"},
        "Superoxide": {"formula": "O2", "charge": "-"},
        "Hydronium": {"formula": "H3O", "charge": "+"}
    }
}

# -----------------------
# SESSION STATE INIT
# -----------------------
defaults = {
    "score": 0,
    "total": 0,
    "streak": 0,
    "high_score": 0,
    "wrong_count": 0,
    "max_wrong": 3,
    "question_id": 0,
    "current_question": None,
    "ask_name_to_formula": None,
    "available_ions": {},
    "question_type": "Both",
    "game_started": False
}

for key, value in defaults.items():
    if key not in st.session_state:
        st.session_state[key] = value

# -----------------------
# HELPER FUNCTIONS
# -----------------------
def select_ions():
    st.sidebar.header("Select Ion Groups")
    available = {}
    for group_name, ions in polyatomic_ions.items():
        group_selected = st.sidebar.checkbox(f"Include {group_name}", value=True)
        if group_selected:
            with st.sidebar.expander(group_name, expanded=True):
                for ion_name, info in ions.items():
                    if st.checkbox(ion_name, value=True):
                        available[ion_name] = info
    st.session_state.available_ions = available
    if not available:
        st.sidebar.warning("Select at least one ion!")

def new_question():
    if not st.session_state.available_ions:
        return
    name, info = random.choice(list(st.session_state.available_ions.items()))
    if st.session_state.question_type == "Both":
        st.session_state.ask_name_to_formula = random.choice([True, False])
    elif st.session_state.question_type == "Formula":
        st.session_state.ask_name_to_formula = True
    else:
        st.session_state.ask_name_to_formula = False
    st.session_state.current_question = (name, info)
    st.session_state.question_id += 1

def check_answer(user_formula, user_charge):
    if not st.session_state.current_question:
        return
    name, info = st.session_state.current_question
    correct_formula = info["formula"]
    correct_charge = info["charge"]

    st.session_state.total += 1
    formula_correct, charge_correct = False, False

    # Check formula / name
    if st.session_state.ask_name_to_formula:
        if user_formula.strip() == correct_formula:
            formula_correct = True
    else:
        valid_names = [name.lower()]
        if name.lower() == "bicarbonate":
            valid_names.append("hydrogen carbonate")
        if user_formula.lower() in valid_names:
            formula_correct = True

    # Check charge (only for formula questions)
    if st.session_state.ask_name_to_formula:
        if user_charge.strip() == correct_charge:
            charge_correct = True
        points = 0
        if formula_correct:
            points += 0.5
        if charge_correct:
            points += 0.5
    else:
        points = 1 if formula_correct else 0

    if points > 0:
        st.session_state.score += points
        st.session_state.streak += 1
        st.success(f"✅ Correct! +{points} points")
    else:
        st.session_state.streak = 0
        st.session_state.wrong_count += 1
        if st.session_state.ask_name_to_formula:
            st.error(f"❌ Incorrect! Formula: {correct_formula}, Charge: {correct_charge}")
        else:
            st.error(f"❌ Incorrect! Name: {name}")

    if st.session_state.score > st.session_state.high_score:
        st.session_state.high_score = st.session_state.score

    if st.session_state.wrong_count >= st.session_state.max_wrong:
        st.warning("💀 Maximum wrong answers reached! Game over.")
        st.session_state.game_started = False
        return

    new_question()

# -----------------------
# MENU SCREEN
# -----------------------
def show_menu():
    st.title("⚛️ Polyatomic Ion Quiz")
    st.subheader("Select Game Settings")

    # Question type
    qtype = st.selectbox(
        "Question Type",
        ["Formula (Name → Formula)", "Name (Formula → Name)", "Both"]
    )
    st.session_state.question_type = {
        "Formula (Name → Formula)":"Formula",
        "Name (Formula → Name)":"Name",
        "Both":"Both"
    }[qtype]

    select_ions()

    if st.button("Start Game"):
        if st.session_state.available_ions:
            st.session_state.game_started = True
            st.session_state.wrong_count = 0
            st.session_state.score = 0
            st.session_state.total = 0
            st.session_state.streak = 0
            new_question()
        else:
            st.warning("Select at least one ion to start!")

# -----------------------
# GAME SCREEN
# -----------------------
def show_game():
    if st.button("⬅ Back to Menu"):
        st.session_state.game_started = False
        return

    st.write(f"**Score:** {st.session_state.score} / {st.session_state.total}")
    st.write(f"**Streak:** {st.session_state.streak} | Wrong: {st.session_state.wrong_count}/{st.session_state.max_wrong}")

    name, info = st.session_state.current_question

    if st.session_state.ask_name_to_formula:
        st.subheader(f"What is the formula and charge for **{name}**?")
    else:
        st.subheader(f"What is the name of the ion with formula **{info['formula']}**?")

    with st.form(key=f"q_{st.session_state.question_id}"):
        user_formula = st.text_input("Formula" if st.session_state.ask_name_to_formula else "Name")
        user_charge = ""
        if st.session_state.ask_name_to_formula:
            user_charge = st.text_input("Charge")
        submitted = st.form_submit_button("Submit")
        if submitted:
            check_answer(user_formula, user_charge)

# -----------------------
# MAIN
# -----------------------
if not st.session_state.game_started:
    show_menu()
else:
    show_game()
